Vagrant.configure("2") do |config|
#  config.vm.box = "debian/stretch64"
#  config.vm.define "figlet" do |fig|
#     fig.vm.hostname = "test-figlet"
#     fig.vm.network "private_network", ip: "192.168.77.202"
#     fig.vm.provision :ansible do |ansible|
#       ansible.limit = "all"
#       #ansible.inventory_path = "test/hosts/vagrant"
#       ansible.playbook = "main.yml"
#    end
#  end

  config.vm.box = "centos/7"
  config.vm.define "figlet_cen" do |figlet_centos|
     figlet_centos.vm.hostname = "figlet-Centos"
     figlet_centos.vm.network "private_network", ip: "192.168.77.203"
     figlet_centos.vm.provision :ansible do |ansible|
       ansible.limit = "all"
       #ansible.inventory_path = "test/hosts/vagrant"
       ansible.playbook = "main.yml"
    end
  end
end

