Vagrant.configure("2") do |config|
#  config.vm.box = "debian/stretch64"
#  config.vm.define "figlet" do |fig|
#     fig.vm.hostname = "test-figlet"
#     fig.vm.network "private_network", ip: "192.168.77.202"
#     fig.vm.provision :ansible do |ansible|
#       ansible.limit = "all"
#       ansible.inventory_path = "test/hosts/vagrant"
#       ansible.playbook = "main.yml"
#    end
#  end

  config.vm.box = "centos/7"
  config.vm.define "figlet_cen"
  config.vm.hostname = "figlet-Centos"

  config.vm.provision "ansible" do |ansible|
     ansible.limit = "all"
     ansible.playbook = "main.yml"
     ansible.host_vars = {
       "figlet_cen" => {"note" => "This is s figlet server running CentOS"}
     }
     ansible.groups = {
       "PRODUCTION" => ["figlet_cen"],
       "PRODUCTION:vars" => {"env" => "PRE-PRODUCTION", "warn" => "This is a pre-prod server - Think about what you are doing and BE CAREFULL"}
      }
  end
end

